# Generated by Django 6.0 on 2026-01-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tontine',
            name='cycle_duration',
            field=models.IntegerField(default=30, help_text='Durée du cycle en jours'),
        ),
        migrations.AddField(
            model_name='tontine',
            name='meeting_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lieu des réunions'),
        ),
        migrations.AddField(
            model_name='tontine',
            name='meeting_schedule',
            field=models.CharField(blank=True, max_length=100, verbose_name='Calendrier des réunions'),
        ),
        migrations.AddField(
            model_name='tontinemember',
            name='role',
            field=models.CharField(choices=[('member', 'Membre'), ('treasurer', 'Trésorier'), ('secretary', 'Secrétaire'), ('vice_president', 'Vice-Président'), ('president', 'Président')], default='member', max_length=20),
        ),
    ]
