# Generated by Django 6.0 on 2026-01-02 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontines', '0002_tontine_cycle_duration_tontine_meeting_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='tontines.tontinemember')),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='tontines.tontine')),
            ],
        ),
    ]
