# Generated by Django 6.0.1 on 2026-01-18 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontines', '0004_vault_wallet_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.IntegerField(default=1, help_text='Numéro du cycle (1ère distribution, 2ème, etc.)')),
                ('allocated_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant de la tontine reçu', max_digits=15)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='tontines.tontinemember')),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='tontines.tontine')),
            ],
            options={
                'unique_together': {('tontine', 'member', 'cycle_number')},
            },
        ),
    ]
