# Generated by Django 6.0 on 2026-01-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin'), ('O', 'Autre')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('woman', 'Femme'), ('man', 'Homme'), ('child', 'Enfant'), ('rural_woman', 'Femme Rurale'), ('student', 'Étudiant'), ('community', 'Association Communautaire'), ('manager', 'Gestionnaire de Tontine')], default='woman', max_length=20),
        ),
    ]
